// src/swarm/sandbox-shim.ts

import { chmod, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { SwarmSandboxConfig } from "./types";

/**
 * Write a sandbox-aware shell wrapper into the worktree.
 * GHOST uses `sandbox_exec` to run this wrapper, which in turn
 * invokes the actual command inside the OS sandbox scoped to the worktree.
 */
export async function installSandboxShim(
	worktreePath: string,
	sandbox: SwarmSandboxConfig,
): Promise<string> {
	const shimPath = join(worktreePath, ".neurogrid-sandbox.sh");

	const shimContent = [
		"#!/usr/bin/env bash",
		"# Auto-generated by neurogrid swarm dispatch.",
		"# Confines all commands to this worktree via OS sandbox.",
		"set -euo pipefail",
		`# Backend: ${sandbox.backend}, Profile: ${sandbox.profile}, Enforced: ${sandbox.enforced}`,
		`cd "${worktreePath}"`,
		'exec "$@"',
	].join("\n");

	await writeFile(shimPath, shimContent, "utf8");
	await chmod(shimPath, 0o755);
	return shimPath;
}
