import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { mkdtemp, readFile, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { installSandboxShim } from "./sandbox-shim";
import type { SwarmSandboxConfig } from "./types";

describe("installSandboxShim", () => {
	let dir: string;

	beforeEach(async () => {
		dir = await mkdtemp(join(tmpdir(), "swarm-shim-test-"));
	});

	afterEach(async () => {
		await rm(dir, { recursive: true, force: true });
	});

	it("writes shim file with expected content", async () => {
		const sandbox: SwarmSandboxConfig = {
			backend: "sandbox-exec",
			profile: "default",
			projectDir: dir,
			enforced: true,
		};

		const shimPath = await installSandboxShim(dir, sandbox);
		const content = await readFile(shimPath, "utf8");

		expect(shimPath).toBe(join(dir, ".neurogrid-sandbox.sh"));
		expect(content).toContain("Auto-generated by neurogrid swarm dispatch");
		expect(content).toContain(
			`# Backend: ${sandbox.backend}, Profile: ${sandbox.profile}, Enforced: ${sandbox.enforced}`,
		);
		expect(content).toContain(`cd "${dir}"`);
		expect(content).toContain('exec "$@"');
	});

	it("marks shim as executable", async () => {
		const sandbox: SwarmSandboxConfig = {
			backend: "bwrap",
			profile: "readonly",
			projectDir: dir,
			enforced: true,
		};

		const shimPath = await installSandboxShim(dir, sandbox);
		const stats = await stat(shimPath);
		expect(stats.mode & 0o111).toBeGreaterThan(0);
	});
});
